### ISSUE TITLE
Add custom scrollbar

### ISSUE THREAD

**Issue by bislara** [bislara/my_portfolio#4]
## Description
Add a customised scroll bar matching to the current theme. 
Maybe a pink colour gradient.

**Comment by wojciechwachowiak** [comment]
Can you please assign this to me?

**Comment by bislara** [comment]
Sure. Go ahead

**Comment by bislara** [comment]
Do follow the [contributing guidelines](https://github.com/bislara/my_portfolio/blob/master/CONTRIBUTING.md)
